juntagrico_assignment_request/urls.py
"""juntagrico_crowdfunding URL Configuration
"""
from django.urls import path
from juntagrico_assignment_request import views

app_name = 'juntagrico-assignment-request'
urlpatterns = [
    path('ar/assignment/request', views.request_assignment, name='request'),
    path('ar/assignment/delete/<int:request_id>/', views.delete_request_assignment, name='delete'),
    path('ar/assignment/edit/<int:request_id>/', views.edit_request_assignment, name='edit'),
    path('ar/assignment/list', views.list_assignment_requests, name='list'),
    path('ar/assignment/archive', views.list_archive, name='archive'),
    path('ar/assignment/respond/<int:request_id>/', views.respond_assignment_request, name='respond'),
    path('ar/assignment/confirm/<int:request_id>/', views.confirm_assignment_request, name='confirm'),
]

juntagrico_assignment_request/models.py
from datetime import datetime, date, time as datetime_time
import time

from django.db import models
from django.db.models import Q
from django.utils.timezone import get_default_timezone
from django.utils.translation import gettext as _
from django.core.validators import MinValueValidator
from juntagrico.entity.location import Location

from juntagrico.entity.member import Member
from juntagrico.entity.jobs import Assignment, ActivityArea, JobType, RecuringJob

from juntagrico.config import Config
from juntagrico.util.temporal import start_of_business_year


class AssignmentQueryset(models.QuerySet):
    def pending(self):
        # assignment requests that have not been replied yet or are from the current business year
        start = datetime.combine(start_of_business_year(), datetime_time.min, tzinfo=get_default_timezone())
        return self.filter(Q(status=AssignmentRequest.REQUESTED) | Q(job_time__gte=start))

    def for_approver(self, member):
        # assignment requests that are requested to this member
        if member.user.has_perm('juntagrico_assignment_request.notified_on_unapproved_assignments'):
            return self.filter(Q(approver=member) | Q(approver__isnull=True))
        return self.filter(approver=member)


class AssignmentRequest(models.Model):
    """
    A request to get an assignment
    """

    JOB_NAME_PREFIX = '_assignment_request_'

    REQUESTED = 'RE'
    REJECTED = 'NO'
    CONFIRMED = 'CO'
    REQUEST_STATUS = [
        (REQUESTED, _('Beantragt')),
        (REJECTED, _('Abgelehnt')),
        (CONFIRMED, _('Bestätigt')),
    ]

    member = models.ForeignKey(Member, verbose_name=Config.vocabulary('member'), on_delete=models.CASCADE,
                               help_text=_("Beantragt von"))
    assignment = models.OneToOneField(Assignment, verbose_name=Config.vocabulary('assignment'),
                                      blank=True, null=True, on_delete=models.PROTECT)

    amount = models.FloatField(
        _('Wert'), default=1, validators=[MinValueValidator(0)],
        help_text=_("Wie viele " + Config.vocabulary('assignment_pl') + "?") + _(
            " Wird mit 'Dauer in Stunden' multipliziert.") if Config.assignment_unit() == 'HOURS' else ''
    )

    job_time = models.DateTimeField(_('Geleistet am'), default=datetime.now)
    request_date = models.DateField(_('Beantragt am'), default=date.today, blank=True, null=True)
    response_date = models.DateField(_('Beantwortet am'), blank=True, null=True,
                                     help_text=_("Typischerweise heute"))
    approver = models.ForeignKey(Member, verbose_name=_('Abgesprochen mit'), related_name=_('Referenz'),
                                 blank=True, null=True, on_delete=models.SET_NULL,
                                 help_text=_("An wen soll die Anfrage gesendet werden oder wer hat "
                                             "dich aufgefordert, die Anfrage zu senden?"))

    description = models.TextField(_('Beschreibung'), max_length=1000, default='',
                                   help_text=_("Kurze Beschreibung, was du gemacht hast"))
    activityarea = models.ForeignKey(ActivityArea, verbose_name=_('Tätigkeitsbereich'),
                                     blank=True, null=True, on_delete=models.SET_NULL,
                                     help_text=_("Was am besten passt. Ansonsten leer lassen"))
    duration = models.DecimalField(_('Dauer in Stunden'), max_digits=4, decimal_places=2, default=4.0)
    location = models.CharField(_('Ort'), max_length=100, blank=True, default='',
                                help_text=_("Optional"))

    status = models.CharField(max_length=2, choices=REQUEST_STATUS, default=REQUESTED,
                              help_text=_('Hier "Bestätigt" auswählen, um die Anfrage anzunehmen'))
    response = models.TextField(_('Antwort'), blank=True, null=True,
                                help_text=_("Rückmeldung an " + Config.vocabulary('member') + ". Kann leer bleiben."))

    objects = AssignmentQueryset.as_manager()

    def __str__(self):
        return _('%s Anfrage #%s') % (Config.vocabulary('assignment'), self.id)

    def is_confirmed(self):
        return self.status == self.CONFIRMED

    def is_rejected(self):
        return self.status == self.REJECTED

    def get_amount(self):
        """
        :return: amount taking into account the assignment unit setting
        """
        if Config.assignment_unit() == 'HOURS':
            return self.amount * float(self.duration)
        return self.amount

    def save(self, **kwargs):
        old_assignment = self.assignment
        super().save(**kwargs)
        # delete assignment object, if request is unconfirmed again
        # this must be done after fully saving the request,
        # because otherwise the assignment is protected by the request
        if old_assignment and not self.assignment:
            self._remove_assignment(old_assignment)

    @classmethod
    def pre_save(cls, sender, instance, **kwds):
        """
        Callback before saving assignment request
        """
        if not kwds.get('raw', False):
            if instance.status == cls.CONFIRMED:
                cls._create_or_update_assignment(instance)
            else:
                instance.assignment = None  # assignment object will be deleted after saving

    def set_activityarea_if_none(self):
        # create/use default activity_area if none specified
        if not self.activityarea:
            self.activityarea, created = ActivityArea.objects.get_or_create(
                name=_('Selbständige Einsätze'),
                defaults={'hidden': True}
            )

    def get_matching_job_type(self):
        # look for autogenerated job type that matches with request
        values = {x: getattr(self, x) for x in ['activityarea']}
        job_type = JobType.objects.filter(
            name__startswith=self.JOB_NAME_PREFIX,
            **values
        )[:1]
        if job_type:
            return job_type[0]
        # create job type if not exists
        location = Location.objects.get_or_create(name=_('Selbständig'), defaults={'visible': False})[0]
        return JobType.objects.create(
            name=f'{self.JOB_NAME_PREFIX}{self.activityarea.id}_{int(time.time())}',  # generate unique job name.
            **values,
            visible=False,
            location=location,
            default_duration=1,  # overridden in job anyways
            displayed_name=_('Selbständiger Einsatz'),
            description=_('Dies ist ein automatisch erzeugter Einsatz.'),
        )

    def get_matching_job(self):
        # create job with job type if not exists
        return RecuringJob.objects.get_or_create(type=self.get_matching_job_type(),
                                                 time=self.job_time,
                                                 duration_override=self.duration,
                                                 defaults={'slots': 1})[0]

    @classmethod
    def _create_or_update_assignment(cls, instance):
        instance.set_activityarea_if_none()

        # assignment
        if instance.assignment:
            # update if exists:
            # saving the assignment will automatically restore its content. If old job is empty after that, remove it.
            instance.assignment.save()
            cls._remove_job(instance.assignment.job)

        else:
            # create new if does not exist
            matching_job = instance.get_matching_job()
            if matching_job.free_slots <= 0:
                matching_job.slots += 1 - matching_job.free_slots
                matching_job.save()
            instance.assignment = Assignment.objects.create(member=instance.member,
                                                            job=matching_job, amount=instance.get_amount())

    @classmethod
    def _remove_assignment(cls, assignment):
        # Delete assignment and job
        assignment.delete()
        cls._remove_job(assignment.job)

    @classmethod
    def _remove_job(cls, job):
        # Delete job, if it has no other assignments
        # the job type is not deleted
        if job.occupied_slots == 0:
            job.delete()
        elif job.free_slots > 0:  # if job stays, remove emptied slot
            job.slots -= 1

    class Meta:
        verbose_name = _('%s Anfrage') % Config.vocabulary('assignment')
        verbose_name_plural = _('%s Anfragen') % Config.vocabulary('assignment')
        permissions = (
            ('can_confirm_assignments', _('Kann selbständige Arbeitseinsätze bestätigen')),
            ('can_confirm_assignments_for_area',
             _('Kann selbständige Arbeitseinsätze im eigenen Tätigkeitsbereich bestätigen')),
            ('notified_on_unapproved_assignments', _('Wird über nicht abgesprochene Arbeitseinsätze informiert')),
        )

juntagrico_assignment_request/views.py
from datetime import date

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _

from juntagrico.view_decorators import highlighted_menu

from juntagrico_assignment_request.forms import AssignmentRequestForm, AssignmentResponseForm
from juntagrico_assignment_request.mailer import membernotification, adminnotification
from juntagrico_assignment_request.models import AssignmentRequest
from juntagrico_assignment_request.view_decorators import approver_required, approver_for_request_required


@login_required
@highlighted_menu('request_assignment')
def request_assignment(request, text_override=None):
    """
    Request an assignment
    """

    text = dict(
        request_sent=_("Deine Anfrage wurde erfolgreich verschickt.<br>"
                       "Du wirst per E-Mail benachrichtigt, sobald diese bestätigt wurde.")
    )
    text.update(text_override or {})

    member = request.user.member
    assignment_request_form = AssignmentRequestForm(request.POST or None)
    if request.method == 'POST' and assignment_request_form.is_valid():
        # Create request
        assignment_request = assignment_request_form.instance
        assignment_request.member = member
        assignment_request.save()
        adminnotification.request_created(assignment_request)
        messages.success(request, mark_safe(text['request_sent']))
        # do a redirect to avoid resending on reloading
        return redirect('juntagrico-assignment-request:request')

    renderdict = {
        'assignment_requests': AssignmentRequest.objects.filter(member=member).pending(),
        'form': assignment_request_form,
    }
    return render(request, "assignment_request/request.html", renderdict)


@login_required
def delete_request_assignment(request, request_id):
    """
    Delete an assignment request
    """

    assignment_request = get_object_or_404(AssignmentRequest, id=request_id)
    if assignment_request.member == request.user.member\
            and not assignment_request.assignment:
        assignment_request.delete()
    return redirect('juntagrico-assignment-request:request')


@login_required
@highlighted_menu('request_assignment')
def edit_request_assignment(request, request_id, text_override=None):
    """
    Edit and assignment request
    """

    text = dict(
        changed=_("Deine Änderungen wurden gespeichert."),
        rerequested=_("Deine Änderungen wurden gespeichert und zur (erneuten) Bestätigung verschickt.")
    )
    text.update(text_override or {})

    member = request.user.member
    assignment_request = get_object_or_404(AssignmentRequest, id=request_id, member=member)
    old_amount = assignment_request.get_amount()
    old_approver = assignment_request.approver
    assignment_request_form = AssignmentRequestForm(request.POST or None, instance=assignment_request)
    if request.method == 'POST' and assignment_request_form.is_valid():
        # edit request
        new_request = assignment_request_form.instance
        if new_request.get_amount() > old_amount:
            # if significant changes were made re-approval is needed
            new_request.status = AssignmentRequest.REQUESTED
            new_request.save()
            adminnotification.request_changed(new_request)
            messages.success(request, text['rerequested'])
        else:
            if new_request.status is not AssignmentRequest.REQUESTED:
                # keep approver, if they replied already
                new_request.approver = old_approver
            new_request.save()
            messages.success(request, text['changed'])
        return redirect('juntagrico-assignment-request:request')

    renderdict = {
        'form': assignment_request_form,
    }
    return render(request, "assignment_request/edit.html", renderdict)


@approver_required
def list_assignment_requests(request):
    """
    List assignment requests
    """
    ar = AssignmentRequest.objects.filter(status=AssignmentRequest.REQUESTED).for_approver(request.user.member)
    renderdict = {
        'assignment_requests': ar,
    }
    return render(request, "assignment_request/list.html", renderdict)


@approver_required
def list_archive(request):
    ar = AssignmentRequest.objects.exclude(status=AssignmentRequest.REQUESTED).for_approver(request.user.member)
    renderdict = {
        'assignment_requests': ar,
        'archive': True
    }
    return render(request, "assignment_request/list.html", renderdict)


@approver_for_request_required
def respond_assignment_request(request, request_id, text_override=None):
    """
    Confirm or reject an assignment request
    """

    text = dict(
        replied=_("Antwort gesendet."),
        already_replied=_("Die Anfrage wurde bereits beantwortet.")
    )
    text.update(text_override or {})

    assignment_request = get_object_or_404(AssignmentRequest, id=request_id)
    if assignment_request.status != AssignmentRequest.REQUESTED:
        messages.warning(request, text['already_replied'])
        return redirect('juntagrico-assignment-request:list')

    assignment_response_form = AssignmentResponseForm(request.POST or None, instance=assignment_request)
    if request.method == 'POST' and assignment_response_form.is_valid():
        assignment_request = assignment_response_form.instance
        assignment_request.response_date = date.today()
        if 'confirm' in request.POST:
            assignment_request.status = AssignmentRequest.CONFIRMED
        elif 'reject' in request.POST:
            assignment_request.status = AssignmentRequest.REJECTED
        adminnotification.request_handled_by_other_approver(assignment_request, request.user.member)
        assignment_request.approver = request.user.member
        assignment_request.save()
        membernotification.request_handled(assignment_request)
        messages.success(request, text['replied'])
        return redirect('juntagrico-assignment-request:list')

    renderdict = {
        'assignment_request': assignment_request,
        'form': assignment_response_form,
    }
    return render(request, "assignment_request/respond.html", renderdict)


@approver_for_request_required
def confirm_assignment_request(request, request_id, text_override=None):
    """
    Confirm an assignment request directly
    """
    text = dict(
        confirmed=_("Anfrage bestätigt."),
        already_confirmed=_("Anfrage bereits bestätigt.")
    )
    text.update(text_override or {})

    assignment_request = get_object_or_404(AssignmentRequest, id=request_id)
    if not assignment_request.is_confirmed():
        assignment_request.response_date = date.today()
        assignment_request.response = ''
        assignment_request.status = AssignmentRequest.CONFIRMED
        adminnotification.request_handled_by_other_approver(assignment_request, request.user.member)
        # overwrite approver in any case to actual approver
        assignment_request.approver = request.user.member
        assignment_request.save()
        membernotification.request_handled(assignment_request)
        messages.success(request, text['confirmed'])
    else:
        messages.warning(request, text['already_confirmed'])
    return redirect('juntagrico-assignment-request:list')

juntagrico_assignment_request/templates/assignment_request/edit.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load juntagrico.config %}
{% load crispy_forms_tags %}
{% block page_title %}
    {% vocabulary "assignment" as v_assignment %}
    <div class="page-title col-md-12">
        <h3>
            {% blocktrans %}{{ v_assignment }} bearbeiten{% endblocktrans %}
        </h3>
    </div>
{% endblock %}
{% block content %}
    {% vocabulary "assignment" as v_assignment %}
    <div class="col-md-12 mb-4">
        {% blocktrans %}Wenn du einen bereits bestätigten {{ v_assignment }} bearbeitest, muss dieser erneut bestätigt werden.{% endblocktrans %}
    </div>
    <div class="col-md-12 mb-4">
        <form action="" method="post" id="request_assignment">
            {% crispy form %}
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ form.approvers_by_area|json_script:'approvers_data' }}
    <script type="text/javascript" src="{% static 'juntagrico_assignment_request/js/request.js' %}"></script>
{% endblock %}

juntagrico_assignment_request/templates/assignment_request/list.html
{% extends "base.html" %}
{% load i18n %}
{% load juntagrico.config %}
{% load crispy_forms_tags %}
{% block page_title %}
    {% vocabulary "assignment_pl" as v_assignment_pl %}
    <div class="page-title col-md-12">
        <h3>
            {% if archive %}
                {% blocktrans %}Beantwortete Anfragen{% endblocktrans %}
            {% else %}
                {% blocktrans %}Angemeldete {{ v_assignment_pl }}{% endblocktrans %}
            {% endif %}
        </h3>
    </div>
{% endblock %}
{% block content %}
    {% if archive %}
    <div class="col-md-12 mb-4">
        <a href="{% url 'juntagrico-assignment-request:list' %}">{% trans "Zurück zu den offenen Anfragen" %}</a>
    </div>
    {% endif %}
    <div class="col-md-12 mb-4">
        {% if assignment_requests %}
        <table id="filter-table" class="list table" style="display: table;">
            <thead>
                <tr>
                    <th class="align-top">
                        {% trans "Einsatz vom" %}
                    </th>
                    <th class="align-top">
                        {% trans "Von" %}
                    </th>
                    <th class="align-top">
                        {% trans "Abgesprochen mit" %}
                    </th>
                    <th class="align-top">
                        {% trans "Status" %}
                    </th>
                    <th class="align-top">
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for assignment_request in assignment_requests %}
                    <tr>
                        <td>
                            {{ assignment_request.job_time|date:"d.m.Y" }}
                        </td>
                        <td>
                            {{ assignment_request.member }}
                        </td>
                        <td>
                            {{ assignment_request.approver|default:"Niemandem" }}
                        </td>
                        <td>
                            {% if assignment_request.assignment.job %}
                                <a href="{% url 'job' assignment_request.assignment.job.id %}">{{ assignment_request.get_status_display }}</a>
                            {% else %}
                                {{ assignment_request.get_status_display }}
                            {% endif %}
                        </td>
                        <td class="text-nowrap">
                            {% if not assignment_request.is_confirmed and not assignment_request.is_rejected %}
                            <a href="{% url 'juntagrico-assignment-request:respond' assignment_request.id %}" class="btn btn-success">Beantworten</a>
                            {% endif %}
                        </td>
                    </tr>
                    <tr class="ar-assignment-request-description">
                        <td colspan="4">
                            <p>{% trans "Beschreibung" %}: {{ assignment_request.description }}</p>
                            {% if assignment_request.response %}<p>{% trans "Antwort" %}: {{ assignment_request.response }}</p>{% endif %}
                        <td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            {% trans "Keine offenen Anfragen an dich" %}
        {% endif %}
    </div>
    <div class="col-md-12 mb-4">
    {% if archive %}
        <a href="{% url 'juntagrico-assignment-request:list' %}">{% trans "Zurück zu den offenen Anfragen" %}</a>
    {% else %}
        <a href="{% url 'juntagrico-assignment-request:archive' %}">{% trans "Beantwortete Anfragen anzeigen" %}</a>
    {% endif %}
    </div>
{% endblock %}

juntagrico_assignment_request/templates/assignment_request/request.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load juntagrico.config %}
{% load crispy_forms_tags %}

{% block page_title %}
   {% vocabulary "assignment" as v_assignment %}
    <div class="page-title col-md-12">
        <h3>
            {% blocktrans %}{{ v_assignment }} melden{% endblocktrans %}
        </h3>
    </div>
{% endblock %}
{% block content %}  
    {% vocabulary "assignment" as v_assignment %}
    {% vocabulary "assignment_pl" as v_assignment_pl %}
    
    <div class="col-md-12 mb-4">
        {% block instructions %}
            {% blocktrans %}
                Hier kannst du deine {{ v_assignment_pl }} melden. 
                Dies gilt für Termine, die nicht mit einer festgelegten Arbeitszeit buchbar sind aber auch
                für selbständige Einsätze. Bitte sprich dich vorgängig mit einer Gartenfachkraft
                oder einer/m Arbeitsgruppen-KoordinatorIn ab, wenn du selbständige Einsätze machen willst.
            {% endblocktrans %}
        {% endblock %}
    </div>

    <div class="col-md-12 mb-4">
        <h4>
            {% blocktrans %}Neue Anfrage erstellen{% endblocktrans %}
        </h4>
    </div>
    <div class="col-md-12 mb-4">
        <form action="" method="post" id="request_assignment">
            {% crispy form %}
        </form>
    </div>

    {% if assignment_requests %}
    <div class="col-md-12 mb-4">
        <h4>
            {% blocktrans %}Gemeldete {{ v_assignment_pl }}{% endblocktrans %}
        </h4>
    </div>
    <div class="col-md-12 mb-4">
        {% blocktrans %}Diese {{ v_assignment_pl }} hast du schon gemeldet (neuste zuerst){% endblocktrans %}

        <table id="filter-table" class="list table" style="display: table;">
            <thead>
                <tr>
                    <th class="align-top">
                        {% trans "Einsatz vom" %}
                    </th>
                    <th class="align-top">
                        {% trans "Abgesprochen mit" %}
                    </th>
                    <th class="align-top">
                        {% trans "Status" %}
                    </th>
                    <th class="align-top">
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for assignment_request in assignment_requests reversed %}
                    <tr>
                        <td>
                            {{ assignment_request.job_time|date:"d.m.Y H:i" }}
                        </td>
                        <td>
                            {{ assignment_request.approver|default:"Niemandem" }}
                        </td>
                        <td>
                            {% if assignment_request.assignment.job %}
                                <a href="{% url 'job' assignment_request.assignment.job.id %}">{{ assignment_request.get_status_display }}</a>
                            {% else %}
                                {{ assignment_request.get_status_display }}
                            {% endif %}
                        </td>
                        <td class="text-nowrap">
                            <a href="{% url 'juntagrico-assignment-request:edit' assignment_request.id %}"
                               class="edit"><i class="bi bi-pencil-square"></i></a>
                            {% if not assignment_request.is_confirmed %}
                            <a href="{% url 'juntagrico-assignment-request:delete' assignment_request.id %}"
                               onclick="return confirm('{% trans 'Bist du sicher, dass du die Anfrage löschen möchtest' %}');"
                               class="delete"><i class="bi bi-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    <tr class="ar-assignment-request-description">
                        <td colspan="3">
                            <p>{% trans "Beschreibung" %}: {{ assignment_request.description }}</p>
                            {% if assignment_request.response %}<p>{% trans "Antwort" %}: {{ assignment_request.response }}</p>{% endif %}
                        <td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% blocktrans %}Es werden nur erledigte Anfragen von dieser Saison und alle offenen Anfragen angezeigt.{% endblocktrans %}
    </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ form.approvers_by_area|json_script:'approvers_data' }}
    <script type="text/javascript" src="{% static 'juntagrico_assignment_request/js/request.js' %}"></script>
{% endblock %}

juntagrico_assignment_request/templates/assignment_request/respond.html
{% extends "base.html" %}
{% load i18n %}
{% load juntagrico.config %}
{% load crispy_forms_tags %}
{% block page_title %}
    {% vocabulary "assignment" as v_assignment %}
    <div class="page-title col-md-12">
        <h3>
            {% blocktrans %}Angemeldeten {{ v_assignment }} beantworten{% endblocktrans %}
        </h3>
    </div>
{% endblock %}
{% block content %}
    <div class="col-md-12 mb-4">
        {% trans "Von:" %} {{ assignment_request.member }}<br>
        {% trans "Beschreibung:" %} {{ assignment_request.description }}<br>
        {% trans "Am:" %} {{ assignment_request.job_time|date:"d.m.Y H:i" }}
    </div>
    <div class="col-md-12 mb-4">
        <form action="" method="post" id="request_assignment">
            {% crispy form %}
        </form>
    </div>
{% endblock %}

juntagrico_assignment_request/templates/assignment_request/respond_assignment_request.html
{% extends "base.html" %}
{% load i18n %}
{% load juntagrico.config %}
{% load crispy_forms_tags %}
{% block page_title %}
    {% vocabulary "assignment" as v_assignment %}
    <div class="page-title col-md-12">
        <h3>
            {% blocktrans %}Angemeldeten {{ v_assignment }} beantworten{% endblocktrans %}
        </h3>
    </div>
{% endblock %}
{% block content %}
    <div class="col-md-12 mb-4">
        {% trans "Von:" %} {{ assignment_request.member }}<br>
        {% trans "Beschreibung:" %} {{ assignment_request.description }}<br>
        {% trans "Am:" %} {{ assignment_request.job_time|date:"d.m.Y H:i" }}
    </div>
    <div class="col-md-12 mb-4">
        <form action="" method="post" id="request_assignment">
            {% crispy form %}
        </form>
    </div>
{% endblock %}